import infographiclogo from 'assets/images/tabler_chart-infographic.svg'
import moneylogo from 'assets/images/tabler_pig-money.svg'
import recieptlogo from 'assets/images/tabler_receipt-tax.png'
import eyelogo from 'assets/images/tabler_eye.svg'
import userlogo from 'assets/images/tabler_man.svg'
import logo from 'assets/images/nova-logo.png'

export const images = [infographiclogo, moneylogo, recieptlogo, eyelogo, userlogo]

export const columnsForLargeTable = [
  { key: 'name', title: '', isIcon: true },
  { key: 'price', title: 'Price' },
  { key: 'volume', title: 'Volume' },
  { key: 'seller', title: 'Seller' },
  { key: 'buyer', title: 'Buyer' },
  { key: 'mc', title: 'Market Cap' },
  { key: 'fdmc', title: 'Fully Diluted MC' },
  { key: 'liquidity', title: 'Liquidity' },
  { key: 'diamondHands', title: 'Diamond Hands' },
  { key: 'paperHands', title: 'Paper Hands' },
  { key: 'uniqueOwners', title: 'Unique Owners' },
]

export const columnsForSmallTable = [
  { key: 'smallTable', title: '' },
  { key: 'index', title: '' },
  { key: 'name', title: '', isIcon: true },
  { key: 'price', title: 'Price' },
  { key: 'volume', title: 'Volume' },
  { key: 'seller', title: 'Seller' },
  { key: 'buyer', title: 'Buyer' },
]

export const data = [
  {
    id: 1,
    name: 'Cardano',
    icon: logo,
    price: '2.50SEI',
    priceChange: '+5.2%',
    volume: '5,00SEI0',
    volumeChange: '-2.1%',
    seller: '2.55SEI', // Seller data (same format as price)
    sellerChange: '+1.8%',
    buyer: '2.45SEI', // Buyer data (same format as price)
    buyerChange: '-0.5%',
    mc: '200B SEI',
    mcChange: '+3.2%',
    fdmc: '250B SEI',
    fdmcChange: '-1.1%',
    liquidity: '1,000SEI',
    liquidityChange: '+2.5%',
    diamondHands: '500SEI',
    diamondHandsChange: '+1.0%',
    paperHands: '750SEI',
    paperHandsChange: '-0.3%',
    uniqueOwners: '10,000SEI',
    uniqueOwnersChange: '+0.8%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 2,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 3,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 4,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 5,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 6,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 7,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
  {
    id: 8,
    name: 'Ethereum',
    icon: logo,
    price: '2,500SEI',
    priceChange: '+2.5%',
    volume: '3,200SEI',
    volumeChange: '-1.5%',
    seller: '2,480SEI', // Seller data (same format as price)
    sellerChange: '-0.8%',
    buyer: '2,520SEI', // Buyer data (same format as price)
    buyerChange: '+1.2%',
    mc: '150B SEI',
    mcChange: '-1.5%',
    fdmc: '180B SEI',
    fdmcChange: '+0.7%',
    liquidity: '800SEI',
    liquidityChange: '+1.8%',
    diamondHands: '450SEI',
    diamondHandsChange: '-0.2%',
    paperHands: '700SEI',
    paperHandsChange: '-1.0%',
    uniqueOwners: '9,500SEI',
    uniqueOwnersChange: '+0.5%',
    volumne: '750',
    holder: '750',
  },
]

export const Graphdata = [
  { month: '15.01.2023', value: 5 },
  { month: '15.02.2023', value: 40 },
  { month: '15.03.2023', value: 15 },
  { month: '15.04.2023', value: 25 },
  { month: '15.05.2023', value: 5 },
  { month: '15.06.2023', value: 1 },
  { month: '15.07.2023', value: 15 },
  { month: '15.08.2023', value: 30 },
  { month: '15.09.2023', value: 20 },
  { month: '15.10.2023', value: 25 },
  { month: '15.11.2023', value: 15 },
  { month: '15.12.2023', value: 10 },
]

export const GraphData2 = [
  {
    name: 'Jan.',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Feb.',
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Mar.',
    uv: 2000,
    pv: 3000,
    amt: 2290,
  },
  {
    name: 'Apr.',
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'May',
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Jun.',
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Aug.',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },

  {
    name: 'Sep.',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },

  {
    name: 'Oct.',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },

  {
    name: 'Nov.',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },

  {
    name: 'Dec.',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
]

export const DonutChartData = [
  { name: 'Category A', value: 400 },
  { name: 'Category B', value: 300 },
  { name: 'Category C', value: 200 },
  { name: 'Category D', value: 500 },
  { name: 'Category E', value: 600 },
]

export const BarChartStackedBySignData = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Page B',
    uv: -3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Page C',
    uv: -2000,
    pv: -9800,
    amt: 2290,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'Page E',
    uv: -1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Page F',
    uv: 2390,
    pv: -3800,
    amt: 2500,
  },
  {
    name: 'Page G',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
]
